name: de-project-specification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Make
        run: sudo apt install make -y
      - name: Run Tests
        env: 
          USERNAME: ${{ secrets.USERNAME}}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ vars.DB_NAME }}
          HOST: ${{ vars.DB_HOST }}
          PORT: ${{ vars.DB_PORT }}
        run: make run-all 
  
  deploy-extract-lambda:
    name: deploy-extract-lambda
    #needs: run-tests
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: extract/terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: extract/terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: extract/terraform
        run: terraform apply -auto-approve

deploy-transform-lambda:
    name: deploy-transfrom-lambda
    # needs: deploy-extract-lambda
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: transform-lambda/terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: transform-lambda/terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: transform-lambda/terraform
        run: terraform apply -auto-approve